baseURL = 'https://fuentedederechocomar.github.io/musica/'
languageCode = 'es-ar'
title = 'inicio'

[menu]
  [[menu.main]]
    pageRef = "search"
    weight = -100
    [menu.main.params]
      type = "search"
  [[menu.main]]
    identifier = "Géneros"
    name = "Géneros"
    url = "/generos/"
    weight = 1
  [[menu.main]]
    identifier = "Compositores"
    name = "Compositores"
    url = "/compositores/"
    weight = 2
  [[menu.main]]
    identifier = "Instrumentos"
    name = "Instrumentos"
    url = "/instrumentos/"
    weight = 3
  [[menu.main]]
    identifier = "Novedades"
    name = "Novedades"
    url = "/novedades/"
    weight = 4
  [[menu.main]]
    identifier = "Etiquetas"
    name = "Etiquetas"
    pageRef = "tags"
    weight = 5

[params]
  description = "Un sitio sobre música"
  pwa = false

  [params.search]
    enable = true

[taxonomies]
  genero = "generos"
  compositor = "compositores"
  instrumento = "instrumentos"
  tag = "tags"

[module]
  [[module.imports]]
    path = "github.com/imfing/hextra"
